#!/bin/sh

cat >test-user-1.js <<EOF
{
  "name":"test-user-1",
  "pw":"oddone23",
  "email":"rlandrum@verisign.com",
  "super_user":"false"
}
EOF
sistool login --node dev.sis.tools.vrsn.com
sistool create user test-user-1.js

